[IV-22-23] Objetivo 6
arsa-dev/OMP-Logic pull request #21
Opened 2022-11-10 10:01 UTC by arsa-dev

* [ ] ¿Se ha evitado Circle CI, porque a estas alturas ya lo ha usado todo el mundo? No, porque a estas alturas no lo ha usado nadie este año.
* [x] ¿Se han establecido criterios *a priori* para elegir el sistema de integración continua más conveniente y se han calificado los sistemas que cumplan esos requisitos según esos criterios?
* [x] ¿Se han examinado varios sistemas de integración continua?
* [x] ¿Se han configurado varios sistemas de integración continua?
* [x] ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar desde los tests)?
* [x] ¿Uno de los sistemas configurados permite comprobar cuales son las versiones del lenguaje con las que funciona correctamente nuestra aplicación?
* [x] ¿Se escogen de forma adecuada las versiones del lenguaje que se testean, tanto en el sistema de CI como en el contenedor Docker?
* [x] ¿Se han justificado correctamente las versiones del lenguaje que se están testeando y se ha comprobado que no se comprueban varias veces lo mismo (la misma versión en CI y en el contenedor Docker en otro sistema CI?

2022-11-10 13:24 UTC, arsa-dev commented
@JJ listo para revisión

2022-11-14 12:07 UTC, JJ requested changes
Correcto, salvo por las versiones.

2022-11-14 12:07 UTC, JJ commented on .github/workflows/unit_test.yml
> +        node-version: ['19.0.1', '18.12.1', '16.18.1', '14.21.1']
No pongas versiones arbitrarias. Ya os dije en clase las tres versiones que había que testear. Aparte, si usas la versión "major" sólo se tomará la última versión minor que corresponda a esa major.

2022-11-14 12:07 UTC, JJ commented on docs/4-test-ci-system.md
> +- Probar la última versión estable actual (v19)
Las impares son de desarrollo, no estables (en el sentido que nunca serán LTS)

2022-11-14 17:00 UTC, arsa-dev commented on .github/workflows/unit_test.yml
> +        node-version: ['19.0.1', '18.12.1', '16.18.1', '14.21.1']
De acuerdo en cuanto a lo de poner solo la major, para no especificar la minor y que por defecto coja la última. Realizo el cambio

2022-11-14 17:00 UTC, arsa-dev commented on docs/4-test-ci-system.md
> +- Probar la última versión estable actual (v19)
Yo entiendo la actual como estable (en este caso la v19), la nightly como no estable de desarrollo, y la lts como versiones de largo soporte que como bien dices son las pares. Es decir lo que llega a versionarse en v19 si sería estable que creo que es en la única en la que no estamos de acuerdo, ¿no?

2022-11-15 08:14 UTC, JJ commented on docs/4-test-ci-system.md
> +- Probar la última versión estable actual (v19)
la *actual* es la 18; es la LTS. Las impares sólo tienen soporte durante ¿6 meses? Algo así.

2022-11-15 08:16 UTC, JJ requested changes
Elimina también la versión que ya estés testeando dentro del contenedor, que no he tenido tiempo de mirar cuál, supongo que la última estable.

2022-11-15 08:16 UTC, JJ commented on .github/workflows/unit_test.yml
> +        node-version: ['19.0', '18.12', '16.18', '14.21']
Sigue siendo la major *y* la minor. El número que has eliminado se llama *patch*.
Con la major solo te tomará la última versión en soporte.

2022-11-15 09:25 UTC, arsa-dev commented on .github/workflows/unit_test.yml
> +        node-version: ['19.0', '18.12', '16.18', '14.21']
Cierto, patiné con el tema, ya está corregido y listo para revisión @JJ

2022-11-15 09:29 UTC, JJ approved these changes
:+1:

2022-11-15 09:29 UTC, JJ commented on docs/decision-making/5-ci-system.md
> +- _Ofrecido como servicio SasS_
Typo: `SaaS`

2022-11-15 09:32 UTC, arsa-dev commented on docs/decision-making/5-ci-system.md
> +- _Ofrecido como servicio SasS_
resuelto también! 🖌️

2022-11-15 09:32 UTC, merged